### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by henrik9999** [clara-j/media_cleaner#1]
````python3 media_cleaner.py 
Traceback (most recent call last):
  File "media_cleaner.py", line 155, in <module>
    deleteItems=get_items(cfg.server_url, cfg.user_key, auth_key)
  File "media_cleaner.py", line 124, in get_items
    item_details=item['Type'] +' - '+ item['Name'] +' - ' + item['UserData']['LastPlayedDate'] + ' - ' + item['UserData']['Key'] + ' - ' + item['Id']
KeyError: 'Key'

**Comment by clara-j** [comment]
I have a new version coming maybe later today that adds support to ignore items marked as favorite.  I will try to get this fixed with that too.

**Comment by henrik9999** [comment]
Any updates?

**Comment by clara-j** [comment]
I have pushed a version that should fix the issue.  Sorry for the delay, been busy with family and work so I just did a bug fix and will work on new version with more features later.

**Comment by terrelsa13** [comment]
@henrik9999 Were you able to get this resolved? I am seeing the same error on a fresh install, as of 2 hours ago.

```bash
Items to be deleted
Traceback (most recent call last):
  File "./media_cleaner.py", line 159, in <module>
    list_items(deleteItems)
  File "./media_cleaner.py", line 145, in list_items
    item_details=item['Name'] + ' - ' + item['UserData']['LastPlayedDate'] + ' - ' + item['UserData']['Key'] + ' - ' + item['Id']
KeyError: 'Key'
```

**Comment by terrelsa13** [comment]
After some playing around with this script I was able to determine ```item['UserData']['Key']``` either never was, or is no longer available thru the API. Removing it resolved the error.


------------------------------------------------------------------------------------------------------------------
**Option#1**
Find this line:
```python
item_details=item['Name'] + ' - ' + item['UserData']['LastPlayedDate'] + ' - ' + item['UserData']['Key'] + ' - ' + item['Id']
```

Make it look like this:
```python
item_details=item['Name'] + ' - ' + item['UserData']['LastPlayedDate'] + ' - ' + item['Id']
```

------------------------------------------------------------------------------------------------------------------
**Option#2**
Comment out or delete the line. If you chose option#2 your media will still be deleted as expected, but you will not get a summary of the deleted media at the end.

You comment out a line by adding # in front of it like this:

```python
#item_details=item['Name'] + ' - ' + item['UserData']['LastPlayedDate'] + ' - ' + item['UserData']['Key'] + ' - ' + item['Id']
```

**Comment by clara-j** [comment]
Let me look into this, I have re-opened the issue.  I thought I had fixed it, but I guess I missed an instance of the Key value.

For some reason on my server I don't have this issue as all items have the Key value.

**Comment by clara-j** [comment]
I just pushed a new version that removed the other Key value.

I had thought the first fix had removed all references to it, but missed the one on that delete command.

Let me know if it is now working for you.

**Comment by terrelsa13** [comment]
Thanks @clara-j that seems to have fixed it.

Now it seems like the emby server side does not like these requests. You ever get this from emby?
[https://pastebin.com/raw/X3jNKqCk](url)

**Comment by clara-j** [comment]
Can you open another issue for this.  I want to resolve this one and we can then discuss in the new ticket but looks like a permission issue.

Make sure the user emby is running under has delete permissions on the files/folders for your media.  I originally had this when I had docker for emby configured as read only for the folder I was using for media.

**Comment by terrelsa13** [comment]
Yep. I will open a new issue.

**Comment by terrelsa13** [comment]
I would also say the original issue posted here is now closed. Unless your update did not solve it for @henrik9999
